AcademyProject/Controllers/CourseController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;
using Models.Constants.NotificationsConstants;

namespace AcademyProject.Controllers
{
    public class CourseController : Controller
    {
        private ICoursesUserService coursesUserService;
        private ISaveCourseUserService saveCourseUserService;
        private UserManager<User> userManager;
        private ICourseService courseService { get; set; }
        public CourseController(ICourseService service, UserManager<User> userManager, ICoursesUserService coursesUserService, ISaveCourseUserService saveCourseUserService)
        {
            this.courseService = service;
            this.userManager = userManager;
            this.coursesUserService = coursesUserService;
            this.saveCourseUserService = saveCourseUserService;
        }

        // Show all courses
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);

            IEnumerable<CourseViewModel> course = this.courseService.GetAll(currentUser.Id);

            CoursesViewModel coursesViewModel = new CoursesViewModel();

            coursesViewModel.Courses = course;

            return this.View(coursesViewModel);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            CourseViewModel course = courseService.GetDetailsById(id);

            bool isCourseNull = course == null;
            if (isCourseNull)
            {
                return this.RedirectToAction("index");
            }
            return this.View(course);
        }

        [HttpGet]
        public async Task<IActionResult> GetCourseById(string id)
        {
            CourseViewModel result =  courseService.GetDetailsById(id);

            return View(@"CoursePartials\_CoursePartial", result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<CourseViewModel> courses = this.courseService.GetByName();

            bool areCoursesEmpty = courses.Count() == 0;
            if (areCoursesEmpty)
            {
                return this.RedirectToAction("index");
            }

            ViewBag.courses = courses;

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseViewModel model)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.RedirectToAction("create");
            }

            Course courseDb = this.courseService.GetByModelName(model.CourseName);

            bool isCourseAlreadyInDb = courseDb != null;
            if (isCourseAlreadyInDb)
            {
                return this.RedirectToAction("index");
            }
            await this.courseService.CreateAsync(model);

            return this.RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            CourseViewModel course = this.courseService.UpdateById(id);

            return this.View(course);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(CourseViewModel model)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.View(model);
            }

            await this.courseService.UpdateAsync(model);

            return this.RedirectToAction("index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            await this.courseService.DeleteAsync(id);

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> Enroll(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyVoted = await this.coursesUserService.EnrollUserToVoteAsync(currentUser.Id, id);

            if (isSuccessfullyVoted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_VOTING;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_VOTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> Disenroll(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyVoted = await this.coursesUserService.RemoveTheUserVoteAsync(currentUser.Id, id);
            if (isSuccessfullyVoted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_UNVOTED;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_UNVOTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> StartCourse(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyStartedd = await this.saveCourseUserService.SaveStartedCourse(currentUser.Id, id);

            if (isSuccessfullyStartedd)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_START_COURSE;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_STARTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> unStarted(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyStarted = await this.saveCourseUserService.RemoveTheCourseAsync(currentUser.Id, id);
            if (isSuccessfullyStarted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_START_COURSE;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_STARTED;
            }

            return this.RedirectToAction("index");
        }
    }
}

AcademyProject/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;
using System.Collections.Generic;

namespace AcademyProject.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;
        public DashboardController(UserManager<User> userManager, IUserService userService)
        {
            _userManager = userManager;
            _userService = userService;
        }

        public IActionResult Index()
        {
            UserViewModel user = _userService.GetDetailsById(ViewBag.userId = _userManager.GetUserId(HttpContext.User));
            return View(user);
        }

        public IActionResult Courses()
        {
            IEnumerable<UserViewModel> courses = _userService.GetAllCourses();

            return PartialView("_CourseDashboardPartial", courses);
        }
        public IActionResult Posts()
        {
            IEnumerable<UserViewModel> posts = _userService.GetAllPosts();

            return PartialView("_PostDashboardPartial", posts);
        }
    }
}

AcademyProject/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;

namespace AcademyProject.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;

        public PostController(IPostService postService, IUserService userService, UserManager<User> userManager)
        {
            this.postService = postService;
            this.userService = userService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<PostViewModel> posts = this.postService.GetAll();

            return this.View(posts);
        }

        public IActionResult Create()
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Post model)
        {
            await postService.CreatePostAsync(
                model.Title,
                model.Context,
                userManager.GetUserName(this.User),
                userManager.GetUserId(this.User));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult LeaveComment()
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            return this.View();
        }
      
        [HttpPost]
        public async Task<IActionResult> LeaveComment(Comment model)
        {
            await postService.LeaveComment(
                model.Context,
                model.Id,
                model.UserName,
                userManager.GetUserId(this.User));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetCommentsAsync(string id)
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            IEnumerable<Comment> comment = this.postService.GetAllCommentByPostId(id);

            return PartialView("PostPartials/_GetComments", comment);
        }
    }
}

AcademyProject/Views/Shared/_CoursesDeleteModel.cshtml
@model CourseViewModel

<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Are you sure you want to delete this chapter?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="text-white" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Chapter title: @Model.CourseName
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a type="button" class="btn btn-danger" asp-area="Designing" asp-controller="Course" asp-action="Delete" asp-route-id="@Model.Id">
                    Confirm delete
                </a>
            </div>
        </div>
    </div>
</div>

AcademyProject/Views/Shared/_FooterPartial.cshtml
<div class="footer_section layout_padding">
    <div class="container">
        <div class="footer_section_2">
            <div class="row">
                <div class="col-lg-3 margin_top">
                    <div class="call_text">
                        <a href="#">
                            <img src="images/call-icon1.png">
                            <span class="padding_left_15">Call Now 202-555-0130</span>
                        </a>
                    </div>
                    <div class="call_text"><a href="#"><img src="images/mail-icon1.png"><span class="padding_left_15">academy@gmail.com</span></a></div>
                </div>
                <div class="col-lg-3">
                    <div class="information_main">
                        <h4 class="information_text">Information</h4>
                        <p class="many_text">There is a great variety of courses.We expect you!!!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="information_main">
                        <h4 class="information_text">Helpful Links</h4>
                        <div class="footer_menu">
                            <ul>
                                <li>
                                    <a class="my-nav-link nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="my-nav-link nav-link" asp-controller="Home" asp-action="About">About Us</a>
                                </li>
                                <li>
                                    <a class="my-nav-link nav-link" asp-controller="Course" asp-action="Index">Courses</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="information_main">
                        <h4 class="information_text">More Info</h4>
                        <p class="many_text">
                            We offer good teachers, good prices and structured courses.You can study online.
                            The choice is yours! We expect you!!!
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AcademyProject/Views/Shared/_Layout.cshtml
@inject SignInManager<Models.Models.User> singInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AcademyProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Course.css" />

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <title>Casinal</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="~/css/animate.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/css/default-skin.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/jquery.fancybox.min.css" rel="stylesheet" />
    <link href="~/css/icomoon.css" rel="stylesheet" />
    <link href="~/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/meanmenu.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/normalize.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link href="~/css/slick.css" rel="stylesheet" />

    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/Course.css" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />

    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
</head>
<body>
    <header>
        <partial name="_MenuPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- footer section start -->
    <partial name="_FooterPartial" />
    <!-- footer section end -->
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery-3.0.0.min.js"></script>
    <script src="js/plugin.js"></script>
    <!-- sidebar -->
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="js/custom.js"></script>
    <!-- javascript -->
    <script src="js/owl.carousel.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AcademyProject/Views/Shared/_MenuPartial.cshtml
@inject SignInManager<Models.Models.User> singInManager;

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="my-nav-link nav-link" asp-controller="Home" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-home"></i></span> Home</a>
                </li>
                <li class="nav-item">
                    <a class="my-nav-link nav-link" asp-controller="Home" asp-action="About"><span class="sidebar-icon"><i class="fa fa-info"></i></span> About Us</a>
                </li>
                <li class="nav-item">
                    <a class="my-nav-link nav-link" asp-controller="Course" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-book"></i></span> Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Post" asp-action="Index" asp-route-id="@singInManager"><span class="sidebar-icon"><i class="fa fa-comment"></i></span> Blog</a>
                </li>
                @if (singInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <a class="my-nav-link nav-link" asp-controller="Dashboard" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-user"></i></span> Dashboard</a>
                    </li>
                }
                <li class="nav-item">
                    <partial name="_LoginPartial" />
                </li>
            </ul>
        </div>
    </nav>
</div>