AcademyProject/Controllers/CourseController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;
using Models.Constants.NotificationsConstants;

namespace AcademyProject.Controllers
{
    public class CourseController : Controller
    {
        private ICoursesUserService coursesUserService;
        private ISaveCourseUserService saveCourseUserService;
        private UserManager<User> userManager;
        private ICourseService courseService { get; set; }
        public CourseController(ICourseService service, UserManager<User> userManager, ICoursesUserService coursesUserService, ISaveCourseUserService saveCourseUserService)
        {
            this.courseService = service;
            this.userManager = userManager;
            this.coursesUserService = coursesUserService;
            this.saveCourseUserService = saveCourseUserService;
        }

        // Show all courses
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);

            IEnumerable<CourseViewModel> course = this.courseService.GetAll(currentUser.Id);

            CoursesViewModel coursesViewModel = new CoursesViewModel();

            coursesViewModel.Courses = course;

            return this.View(coursesViewModel);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            CourseViewModel course = courseService.GetDetailsById(id);

            bool isCourseNull = course == null;
            if (isCourseNull)
            {
                return this.RedirectToAction("index");
            }
            return this.View(course);
        }

        [HttpGet]
        public async Task<IActionResult> GetCourseById(string id)
        {
            CourseViewModel result =  courseService.GetDetailsById(id);

            return View(@"CoursePartials\_CoursePartial", result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<CourseViewModel> courses = this.courseService.GetByName();

            bool areCoursesEmpty = courses.Count() == 0;
            if (areCoursesEmpty)
            {
                return this.RedirectToAction("index");
            }

            ViewBag.courses = courses;

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseViewModel model)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.RedirectToAction("create");
            }

            Course courseDb = this.courseService.GetByModelName(model.CourseName);

            bool isCourseAlreadyInDb = courseDb != null;
            if (isCourseAlreadyInDb)
            {
                return this.RedirectToAction("index");
            }
            await this.courseService.CreateAsync(model);

            return this.RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            CourseViewModel course = this.courseService.UpdateById(id);

            return this.View(course);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(CourseViewModel model)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.View(model);
            }

            await this.courseService.UpdateAsync(model);

            return this.RedirectToAction("index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            await this.courseService.DeleteAsync(id);

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> Enroll(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyVoted = await this.coursesUserService.EnrollUserToVoteAsync(currentUser.Id, id);

            if (isSuccessfullyVoted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_VOTING;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_VOTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> Disenroll(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyVoted = await this.coursesUserService.RemoveTheUserVoteAsync(currentUser.Id, id);
            if (isSuccessfullyVoted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_UNVOTED;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_UNVOTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> StartCourse(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyStartedd = await this.saveCourseUserService.SaveStartedCourse(currentUser.Id, id);

            if (isSuccessfullyStartedd)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_START_COURSE;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_STARTED;
            }

            return this.RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> unStarted(string id)
        {
            User currentUser = await this.userManager.GetUserAsync(this.User);

            bool isSuccessfullyStarted = await this.saveCourseUserService.RemoveTheCourseAsync(currentUser.Id, id);
            if (isSuccessfullyStarted)
            {
                this.TempData[NotificationsConstants.SUCCESS_NOTIFICATION] = NotificationsConstants.SUCCESSFUL_START_COURSE;
            }
            else
            {
                this.TempData[NotificationsConstants.WARNING_NOTIFICATION] = NotificationsConstants.ALREADY_STARTED;
            }

            return this.RedirectToAction("index");
        }
    }
}

AcademyProject/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;
using System.Collections.Generic;

namespace AcademyProject.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;
        public DashboardController(UserManager<User> userManager, IUserService userService)
        {
            _userManager = userManager;
            _userService = userService;
        }

        public IActionResult Index()
        {
            UserViewModel user = _userService.GetDetailsById(ViewBag.userId = _userManager.GetUserId(HttpContext.User));
            return View(user);
        }

        public IActionResult Courses()
        {
            IEnumerable<UserViewModel> courses = _userService.GetAllCourses();

            return PartialView("_CourseDashboardPartial", courses);
        }
        public IActionResult Posts()
        {
            IEnumerable<UserViewModel> posts = _userService.GetAllPosts();

            return PartialView("_PostDashboardPartial", posts);
        }
    }
}

AcademyProject/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

using Models.Models;
using Services.Interfaces;
using Services.ViewModels;

namespace AcademyProject.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;

        public PostController(IPostService postService, IUserService userService, UserManager<User> userManager)
        {
            this.postService = postService;
            this.userService = userService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<PostViewModel> posts = this.postService.GetAll();

            return this.View(posts);
        }

        public IActionResult Create()
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Post model)
        {
            await postService.CreatePostAsync(
                model.Title,
                model.Context,
                userManager.GetUserName(this.User),
                userManager.GetUserId(this.User));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult LeaveComment()
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            return this.View();
        }
      
        [HttpPost]
        public async Task<IActionResult> LeaveComment(Comment model)
        {
            await postService.LeaveComment(
                model.Context,
                model.Id,
                model.UserName,
                userManager.GetUserId(this.User));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetCommentsAsync(string id)
        {
            this.ViewData["Users"] = userService.GetAllUsernames(userManager.GetUserId(this.User));
            IEnumerable<Comment> comment = this.postService.GetAllCommentByPostId(id);

            return PartialView("PostPartials/_GetComments", comment);
        }
    }
}

AcademyProject/Controllers/TopCoursesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Services.ViewModels.RankingViewModels;

using Services.Interfaces;

namespace AcademyProject.Controllers
{
    public class TopCoursesController : Controller
    {
        private readonly ITopCoursesService topCoursesService;

        public TopCoursesController(ITopCoursesService topCoursesService)
        {
            this.topCoursesService = topCoursesService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            IEnumerable<TopCourseViewModel> course = this.topCoursesService.GetAll();

            GetAllTopCoursesViewModel allCourses = new GetAllTopCoursesViewModel();
            allCourses.Courses = course;

            return this.View(allCourses);
        }
    }
}

AcademyProject/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Services.Interfaces;
using Services.ViewModels;

namespace AcademyProject.Controllers
{
    public class UserController : Controller
    {
        public IUserService userService { get; set; }

        public UserController(IUserService service)
        {
            userService = service;
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            UserViewModel user = userService.GetDetailsById(id);
            return View(user);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            UserViewModel user = userService.GetDetailsById(id);

            bool isUserNull = user == null;
            if (isUserNull)
            {
                return this.RedirectToAction("index");
            }
            return this.View("index" , user);
        }


        [HttpGet]
        public IActionResult Update(string id)
        {
            UserViewModel user = this.userService.UpdateById(id);

            return this.View(user);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(UserViewModel model)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.View(model);
            }

            await this.userService.UpdateAsync(model);

            return View(@"UserPartials\_UpdateUserAlert");
        }
    }
}

AcademyProject/Views/Dashboard/Index.cshtml
@model UserViewModel

@inject SignInManager<Models.Models.User> singInManager;

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="~/css/DashCss/dashStyle.css" rel="stylesheet" />

<div class="page-topbar">
    <div class="quick-area">
        <ul class="pull-right info-menu user-info">
                        <li class="nav-item active">
                            <a class="my-nav-link nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="my-nav-link nav-link" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="my-nav-link nav-link" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="my-nav-link nav-link" asp-controller="Post" asp-action="Index">Blog</a>
                        </li>
            <li class="profile">
                <a href="#" data-toggle="dropdown" class="toggle" aria-expanded="false">
                    <img class="cardPhoto" src="@("~/ImageForUser/" + Model.ImageName)" asp-append-version="true" />
                    <span>@Model.UserName </span>
                </a>
                <ul class="dropdown-menu profile fadeIn ">
                    <li>
                        <a class="options-bar" asp-controller="User" asp-action="Details" asp-route-id="@Model.Id">
                            Profile
                        </a>
                    </li>

                    <li class="last">
                        <a class="my-nav-link nav-link" asp-controller="Home" asp-action="Index">Back</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="page-sidebar" style="position:absolute">
    <div class="sidebar-inner" id="main-menu-wrapper">
        <div class="profile-info row ">
            <div class="profile-details">
                <h3>
                    <a href="ui-profile.html">@Model.UserName</a>
                </h3>
                <p class="profile-title">@Model.Profession</p>

            </div>
        </div>

        <ul class="wraplist" style="height: auto;">
            <li><a href=""><span class="sidebar-icon"><i class="fa fa-dashboard"></i></span> <span class="menu-title">Dashboard</span></a></li>
            @if (singInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <li><a class="my-nav-link" asp-controller="Course" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-lock"></i></span><span class="menu-title">Manage Courses</span></a></li>
            }
            <li> <a class="my-nav-link" asp-controller="TopCourses" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-thumbs-up"></i></span> <span class="menu-title">Top Courses</span></a></li>
            <li> <a class="my-nav-link" asp-controller="Post" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-bell"></i></span> <span class="menu-title">Forum</span></a></li>
            <li> <a class="my-nav-link nav-link" asp-controller="Home" asp-action="Index"><span class="sidebar-icon"><i class="fa fa-sign-out"></i></span> <span class="menu-title">Sign Out</span></a></li>
        </ul>
    </div>
</div>

<section id="main-content">
    <section class="wrapper main-wrapper row">
            
            <div class="col-md-6">
                <section class="box">
                    <h5>Course List</h5>
                    <button id="courses" class="btn btn-danger">Show all Courses</button>
                    <div id="courseContent">

                    </div>
                </section>
            </div>
 
            <div class="clearfix"></div>

            <div class="col-md-12">
                <section class="box">
                    <h5>Show all Posts</h5>
                    <button id="posts" class="btn btn-danger">Show all Posts</button>
                    <div id="content">

                    </div>
                </section>
            </div>

        </section>
</section>

@section Scripts{
    <script>
        $("#posts").on("click", function () {
            $.ajax({
                method: "GET",
                url: "Dashboard/Posts",
                success: function (data) {
                    $("#content").html(data);
                },
                error: function (err) {
                    alert(err);
                }
            });
        })
    </script>

    <script>
        $("#courses").on("click", function () {
            $.ajax({
                method: "GET",
                url: "Dashboard/Courses",
                success: function (data) {
                    $("#courseContent").html(data);
                },
                error: function (err) {
                    alert(err);
                }
            });
        })
    </script>
}

AcademyProject/Views/Dashboard/_CourseDashboardPartial.cshtml
@model List<UserViewModel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Duration</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.CourseName</td>
                <td>@item.CourseDuration</td>
                <td>@item.CoursePrice</td>
            </tr>
        </tbody>
    }
</table>

AcademyProject/Views/Dashboard/_PostDashboardPartial.cshtml
@model List<UserViewModel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">By:</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.PostTitle</td>
                <td>@item.UserName</td>
            </tr>
        </tbody>
    }
</table>

AcademyProject/Views/Dashboard/_StudentDashboardPartial.cshtml
@model List<UserViewModel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.StudentFirstName</td>
                <td>@item.StudentSecondName</td>
                <td>@item.StudentLastName</td>
            </tr>
        </tbody>
    }
</table>